export const applyBranding = (dataUrl: string, title: string): Promise<string> =>
  new Promise(resolve => {
    const image = new Image();
    image.onload = () => {
      const canvas = document.createElement('canvas');
      canvas.width = image.width;
      canvas.height = image.height;
      const context = canvas.getContext('2d');

      if (!context) {
        resolve(dataUrl);
        return;
      }

      context.drawImage(image, 0, 0);

      const barHeight = canvas.height * 0.08;
      context.fillStyle = 'rgba(15, 23, 42, 0.8)';
      context.fillRect(0, canvas.height - barHeight, canvas.width, barHeight);

      const padding = 40;
      context.fillStyle = '#ffffff';
      context.font = `bold ${Math.floor(barHeight * 0.4)}px Inter, sans-serif`;
      context.textAlign = 'left';
      context.fillText(title.toUpperCase(), padding, canvas.height - barHeight / 2 + barHeight * 0.1);

      context.fillStyle = 'rgba(255, 255, 255, 0.5)';
      context.font = `${Math.floor(barHeight * 0.25)}px Inter, sans-serif`;
      context.textAlign = 'right';
      context.fillText('GENERATED BY JOZOR', canvas.width - padding, canvas.height - barHeight / 2 + barHeight * 0.1);

      resolve(canvas.toDataURL('image/png'));
    };
    image.src = dataUrl;
  });
