import { formatDateForPostgres } from '../utils/dateUtils';
export const buildPersonCustomFields = (person) => ({
    title: person.title,
    birthSource: person.birthSource,
    deathSource: person.deathSource,
    burialPlace: person.burialPlace,
    residence: person.residence,
    marriageDate: person.marriageDate || '',
    marriagePlace: person.marriagePlace || '',
    gallery: person.gallery || [],
    voiceNotes: person.voiceNotes || [],
    sources: person.sources || [],
    events: person.events || [],
    partnerDetails: person.partnerDetails || {},
    isPrivate: !!person.isPrivate,
});
export const mapDbPersonRowToPerson = (row) => {
    const customFields = row.custom_fields || {};
    const metadata = row.metadata || {};
    return {
        ...metadata,
        id: row.id,
        title: customFields.title ?? '',
        firstName: row.first_name ?? '',
        middleName: row.middle_name ?? '',
        lastName: row.last_name ?? '',
        birthName: row.birth_name ?? '',
        nickName: row.nick_name ?? '',
        suffix: row.suffix ?? '',
        gender: row.gender ?? 'male',
        birthDate: row.birth_date ?? '',
        birthPlace: row.birth_place ?? '',
        birthSource: customFields.birthSource ?? '',
        marriageDate: customFields.marriageDate ?? '',
        marriagePlace: customFields.marriagePlace ?? '',
        deathDate: row.death_date ?? '',
        deathPlace: row.death_place ?? '',
        deathSource: customFields.deathSource ?? '',
        isDeceased: !!row.death_date || !!customFields.isDeceased,
        profession: row.profession ?? '',
        company: row.company ?? '',
        interests: row.interests ?? '',
        bio: row.bio ?? '',
        photoUrl: row.photo_url ?? undefined,
        gallery: Array.isArray(customFields.gallery) ? customFields.gallery : [],
        voiceNotes: Array.isArray(customFields.voiceNotes) ? customFields.voiceNotes : [],
        sources: Array.isArray(customFields.sources) ? customFields.sources : [],
        events: Array.isArray(customFields.events) ? customFields.events : [],
        email: row.email ?? '',
        website: row.website ?? '',
        blog: row.blog ?? '',
        address: row.address ?? '',
        parents: [],
        spouses: [],
        children: [],
        burialPlace: customFields.burialPlace ?? '',
        residence: customFields.residence ?? '',
        partnerDetails: customFields.partnerDetails ?? undefined,
        isPrivate: customFields.isPrivate ?? false,
    };
};
export const mapPersonToDbRow = (person, treeId) => {
    const { parents: _parents, spouses: _spouses, children: _children, ...metadata } = person;
    return {
        metadata,
        id: person.id,
        ...(treeId ? { tree_id: treeId } : {}),
        first_name: person.firstName || '',
        last_name: person.lastName || '',
        middle_name: person.middleName || null,
        birth_name: person.birthName || null,
        nick_name: person.nickName || null,
        suffix: person.suffix || null,
        gender: person.gender || 'male',
        birth_date: formatDateForPostgres(person.birthDate),
        death_date: formatDateForPostgres(person.deathDate),
        birth_place: person.birthPlace || null,
        death_place: person.deathPlace || null,
        bio: person.bio || null,
        profession: person.profession || null,
        company: person.company || null,
        interests: person.interests || null,
        photo_url: person.photoUrl || null,
        email: person.email || null,
        website: person.website || null,
        blog: person.blog || null,
        address: person.address || null,
        custom_fields: buildPersonCustomFields(person),
    };
};
