export const KINDI_LEARNING_FAILURE_REASONS = {
  UNKNOWN_DIALECT_WORD: 'UNKNOWN_DIALECT_WORD',
  NAME_AMBIGUOUS: 'NAME_AMBIGUOUS',
  FIELD_NOT_RECOGNIZED: 'FIELD_NOT_RECOGNIZED',
  RELATION_NOT_SUPPORTED: 'RELATION_NOT_SUPPORTED',
  LOCAL_SEARCH_FAILED: 'LOCAL_SEARCH_FAILED',
  AI_LOW_CONFIDENCE: 'AI_LOW_CONFIDENCE',
  USER_CANCELLED: 'USER_CANCELLED',
  USER_REJECTED_DRAFT: 'USER_REJECTED_DRAFT',
  SUPPORT_TOPIC_MISSING: 'SUPPORT_TOPIC_MISSING',
  PARSER_PATTERN_MISSING: 'PARSER_PATTERN_MISSING',
  EXECUTION_FAILED: 'EXECUTION_FAILED',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
} as const;

export type KindiLearningFailureReason =
  typeof KINDI_LEARNING_FAILURE_REASONS[keyof typeof KINDI_LEARNING_FAILURE_REASONS];

export type KindiParserStage =
  | 'intent_router'
  | 'local_search'
  | 'command_planner'
  | 'ai_fallback'
  | 'confirmation'
  | 'disambiguation'
  | 'support_guide'
  | 'execution';
